config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :users, except: [:index, :new]
  resources :recipes
  
  get '/register', to: 'users#new'
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  get "/logout", to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  include Sluggable
  
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  
  validates :name, presence: true
  
  sluggable_property(:name)
  
  def total_time
    prep_time + cook_time
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'securerandom'
  
  has_many :recipes
  
  validates :email, presence: true, uniqueness: true
  validates :zip, presence: true, length: { is: 5 }
  validates :password, length: { minimum: 6 }
  
  has_secure_password
  
  before_create :create_slug
  
  def to_param
    self.slug
  end
  
  private
    def create_slug
      sample_slug = SecureRandom.hex(4)
      if User.find_by(slug: sample_slug)
        create_slug
      else
        self.slug = sample_slug
      end
    end
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ADMIN_IDS = [2]
  
  protect_from_forgery with: :exception
  
  helper_method :logged_in?, :current_user
  
  def current_user
    @current_user ||= session[:user_id] ? User.find(session[:user_id]) : nil
  end
  
  def logged_in?
    !!current_user
  end
  
  def redirect_logged_out
    if !logged_in?
      flash[:danger] = "You must be logged in to do that."
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :redirect_logged_out, except: [:index, :show]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  
  def index
    @recipes = Recipe.where(user_id: [current_user.id, ADMIN_IDS].flatten)
  end
  
  def show
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.creator = current_user
    
    if @recipe.save
      flash[:success] = "Recipe successfully created."
      redirect_to recipes_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
  
  private
    def recipe_params
      params.require(:recipe).permit(:name, :prep_time, :cook_time, :url, :instructions)
    end
    
    def set_recipe
      @recipe = Recipe.find_by(slug: params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      flash[:success] = "Welcome, you've logged in."
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:danger] = "Incorrect Username and/or Password"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You've logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def show
  end
  
  def new
    @user = User.new
    
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "You have successfully registered."
      session[:user_id] = @user.id
      redirect_to :root
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @user.update(user_params)
      flash["success"] = "You have updated your profile."
      redirect_to :root
    else
      render 'edit'
    end
  end
  
  def destroy
  end
  
  private
    def user_params
      params.require(:user).permit(:email, :zip, :password)
    end
    
    def set_user
      @user = User.find_by(slug: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Recipe Tracker</h1>
    <p class="lead">Keep track of all your recipes and explore great meals from across the world.</p>
    <% if !logged_in? %>
      <%= link_to "Join Now!", register_path, class: 'btn btn-primary btn-lg join' %>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'success' ? 'success' : 'danger' %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav justify-content-center">
  <li class="nav_item">
    <%= link_to "Home", root_path, :class => 'brand btn btn-primary' %>
  </li>
  <% if logged_in? %>
    <li class="nav_item">
      <%= link_to 'View Recipes', recipes_path, class: "btn btn-success btn-small" %>
    </li>
    <li class="nav_item">
      <%= link_to 'New Recipe', new_recipe_path, class: "btn btn-success btn-small" %>
    </li>
    <li class="btn-group nav_item">
      <%= link_to '#', class: "btn btn-small btn-secondary dropdown-toggle", "data-toggle": "dropdown" do %>
        User Options <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li>
          <%= link_to edit_user_path(current_user) do %>
            <i class="icon-pencil"></i>
            edit profile
          <% end %>
        </li>
        <li>
          <%= link_to logout_path do %>
            <i class="icon-circle-arrow-left"></i>
            logout
          <% end %>
        </li>
      </ul>
    </li>
  <% else %>
    <li class="nav_item">
      <%= link_to 'Register', register_path, class: "btn btn-success btn-small" %>
    </li>
    <li class="nav_item">
      <%= link_to 'Login', login_path, class: "btn btn-success btn-small" %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="row">
  <div class='card col-6 d-inline-block'>
    <div class="card-block">
      <%= form_for @recipe do |f| %>
        <h5>Recipe Info</h5>
        <div class="form-group">
          <%= f.label :name, "Recipe Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :prep_time, "Prep Time (minutes)" %>
          <%= f.number_field :prep_time, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :cook_time, "Cook Time (minutes)" %>
          <%= f.number_field :cook_time, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :instructions %>
          <%= f.text_area :instructions, class: "form-control", rows: 6 %>
        </div>
        <div class="form-group">
          <%= f.label :url, "Link to Recipe URL" %>
          <%= f.url_field :url, class: "form-control" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="card col-6 d-inline-block ingredient_container">
    <div class="card-block">
      <%= form_tag('/recipe_ingredients', method: 'post') do %>
        <h5>Ingredients</h5>
        <div class="form-group row ingredient_input">
          <div class="col-2">
            <%= label_tag('quantity') %>
            <%= text_field_tag('quantity', nil, class: 'form-control', name: 'quantity[]') %>
          </div>
          <div class="col-3">
            <%= label_tag('unit') %>
            <%= select_tag('unit', options_for_select(['ml', 'lb']), class: 'form-control', name: 'unit[]') %>
          </div>
          <div class="col-5">
            <%= label_tag('name') %>
            <%= text_field_tag('name', nil, class: 'form-control', name: 'name[]') %>
          </div>
          <div class="col-2">
            <%= label_tag('delete') %>
            <button type="button" id="delete" class="btn btn-danger delete_ingredient" aria-label="Delete">
              <i class="fa fa-minus-circle"></i>
            </button>
          </div>
        </div>
        <div class="form-group row mt-4 ml-1">
            <h5 class="align-middle d-inline-block mr-3">Add Ingredient</h5>
            <a href="#" class="btn btn-primary add_ingredient"><i class="fa fa-plus-circle"></i></a>
        </div>
        <a href="#" class="new_ingredient">Can't find ingredient? Add your own.</a>
      <% end %>
    </div>
  </div>
  <div class="card-block text-center">
      <button type="button" class="btn btn-primary btn-lg submit_recipe">Create Recipe</button>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div class="row">
  <h5 class="mr-3"><%= link_to recipe.name, recipe_path(recipe) %></h5>
  <p class="mr-3">Prep Time: <%= recipe.prep_time %></p>
  <p class="mr-3">Cook Time: <%= recipe.cook_time %></p>
  <p class="">Total Time: <%= recipe.total_time %></p>
</div>
<% if action == 'show' %>
  <div class="card">
    <div class="card-block">
      <p><%= recipe.instructions %></p>
    </div>
  </div>
<% end %>

app/views/recipes/index.html.erb
<%= render 'shared/title', title: "Recipes" %>

<% @recipes.each do |recipe| %>
  <%= render 'recipe', recipe: recipe, action: 'index' %>
<% end %>

app/views/recipes/new.html.erb
<%= render 'shared/title', title: "New Recipe" %>

<%= render 'shared/errors', model: @recipe %>

<%= render 'form', action: 'new' %>

app/views/recipes/show.html.erb
<%= render 'shared/title', title: @recipe.name %>

<%= render 'recipe', recipe: @recipe, action: 'show' %>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-6" role="alert">
      <h5>
        <%= pluralize(model.errors.count, "error") %>:
      </h5>
      <ul>
        <% model.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_title.html.erb
<h3>
  <%= title %>
  <hr/>
</h3>

app/views/users/_form.html.erb
<div class='card col-6'>
  <div class="card-block">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :zip, "Zip Code" %>
        <%= f.text_field :zip, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, "Create a password" %>
        <%= f.password_field :password, class: "form-control", placeholder: "Minimum 6 characters" %>
      </div>
      <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/title', title: "Edit Profile" %>

<%= render 'shared/errors', model: @user %>

<%= render 'form', action: 'edit' %>

app/views/users/new.html.erb
<%= render 'shared/title', title: "Register" %>

<%= render 'shared/errors', model: @user %>

<%= render 'form', action: 'new' %>